### ISSUE TITLE
Debug mode: Messages

### ISSUE THREAD

**Issue by frase-git** [cmb69/uploader_xh#14] opened 2021-03-30 07:45 UTC
XH 1.7.4
PHP 7.4.2
When calling the plugin configuration, the following messages appear:

> NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
> ... \plugins\uploader\config\metaconfig.php:5
> NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
> ... \plugins\uploader\config\metaconfig.php:6
> NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
> ... \plugins\uploader\config\metaconfig.php:7
> NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
> ... \plugins\uploader\config\metaconfig.php:8

**Comment by cmb69** [comment] 2021-03-30 09:18
Oh, I fixed that long ago (b5066a0a573a31a20e47b17427d45abf1f57aa2c), but apparently didn't release a new version. Anyhow, this is a duplicate of #10.

**Closed by cmb69** 2021-03-30 09:18 UTC

**Comment by frase-git** [comment] 2021-03-30 09:28
Sorry, I had not seen https://github.com/cmb69/uploader_xh/issues/10.
Then everything is fine ;-)
